export interface CaseStudy {
  id: string;
  solutionSlug: string;
  // 基本信息（脱敏）
  name: string; // e.g. "张先生"
  age: number;
  location: string; // e.g. "上海"
  // Before/After
  beforeState: string[];
  afterState: string[];
  duration: string; // e.g. "服用4周后"
  timeline: string; // e.g. "2024年3月"
  // 引用
  quote: string;
  // 产品
  products: string[];
}

export const caseStudies: CaseStudy[] = [
  // ===== 睡眠方案 =====
  {
    id: "sleep-case-1",
    solutionSlug: "sleep",
    name: "李女士",
    age: 34,
    location: "深圳",
    beforeState: ["睡眠浅容易醒", "白天精神不济", "日常注意力难以集中"],
    afterState: ["睡眠节律有所改善", "日常精神状态有所恢复", "日常工作精力有所提升"],
    duration: "服用甘氨酸镁+GABA 4周后",
    timeline: "2024年3月",
    quote: "搭配营养师推荐的方案后，日常精神状态有明显提升，整体生活品质有所改善。",
    products: ["甘氨酸镁", "GABA"],
  },
  {
    id: "sleep-case-2",
    solutionSlug: "sleep",
    name: "王先生",
    age: 41,
    location: "北京",
    beforeState: ["经常加班到凌晨1-2点", "应酬后更难入睡", "周末也感觉休息不好"],
    afterState: ["日常入睡节奏有所改善", "周末休息质量有所提升", "整体日常精力有所恢复"],
    duration: "服用茶氨酸+镁 6周后",
    timeline: "2024年5月",
    quote: "顾问分析了我的作息特点，调整了服用时间，日常睡眠节奏有所改善。",
    products: ["茶叶茶氨酸", "甘氨酸镁"],
  },
  {
    id: "sleep-case-3",
    solutionSlug: "sleep",
    name: "孙女士",
    age: 28,
    location: "上海",
    beforeState: ["入睡前思绪繁多", "夜间容易醒来", "白天需要依赖咖啡"],
    afterState: ["入睡前的放松感有所改善", "夜间睡眠连续性有所提升", "日常咖啡饮用量有所减少"],
    duration: "服用甘氨酸镁+GABA 5周后",
    timeline: "2024年4月",
    quote: "顾问根据我的情况调整了方案，日常作息节奏有明显改善，整体精力状态有所恢复。",
    products: ["甘氨酸镁", "GABA"],
  },
  // ===== 疲劳恢复方案 =====
  {
    id: "fatigue-case-1",
    solutionSlug: "fatigue",
    name: "陈先生",
    age: 38,
    location: "广州",
    beforeState: ["午后容易疲劳犯困", "运动后恢复较慢", "体检显示亚健康指标"],
    afterState: ["午后精神状态有所改善", "运动后恢复速度有所加快", "整体精力状态有所恢复"],
    duration: "服用辅酶Q10+B族 8周后",
    timeline: "2024年4月",
    quote: "营养师根据我的日常作息和饮食特点，推荐了针对性的营养补充方案，整体状态有所改善。",
    products: ["辅酶Q10", "B族维生素"],
  },
  {
    id: "fatigue-case-2",
    solutionSlug: "fatigue",
    name: "张女士",
    age: 29,
    location: "上海",
    beforeState: ["长期熬夜做项目", "面色暗沉", "近期体检显示部分指标偏高"],
    afterState: ["整体气色有所改善", "日常精力有所恢复", "日常工作专注力有所提升"],
    duration: "服用Omega-3+复合维生素 10周后",
    timeline: "2024年6月",
    quote: "营养师分析了我的饮食结构后，推荐了针对性的补充方案，日常状态有明显改善。",
    products: ["Omega-3", "复合维生素"],
  },
  {
    id: "fatigue-case-3",
    solutionSlug: "fatigue",
    name: "高先生",
    age: 33,
    location: "南京",
    beforeState: ["应酬多、经常饮酒", "饮酒后第二天难以正常工作", "体检显示部分肝指标异常"],
    afterState: ["饮酒后第二天状态恢复速度有所加快", "整体精力状态有所改善", "日常应酬后恢复更快"],
    duration: "服用辅酶Q10+NAC 12周后",
    timeline: "2024年3月",
    quote: "顾问帮我分析了应酬规律，推荐了针对性的营养支持方案，饮酒后的日常恢复有明显改善。",
    products: ["辅酶Q10", "N-乙酰半胱氨酸"],
  },
  // ===== 肝脏支持方案 =====
  {
    id: "liver-case-1",
    solutionSlug: "liver",
    name: "刘先生",
    age: 45,
    location: "成都",
    beforeState: ["每周应酬3-4次", "饮酒后第二天难以正常工作", "体检显示轻度脂肪倾向"],
    afterState: ["饮酒后第二天状态恢复速度有所加快", "整体气色有所改善", "日常精力有所恢复"],
    duration: "服用水飞蓟宾+NAC 12周后",
    timeline: "2024年2月",
    quote: "应酬多的老毛病了，没想到营养补充配合调整作息真的有改善。顾问让我搭配复合B族，现在状态好多了。",
    products: ["水飞蓟宾", "N-乙酰半胱氨酸", "B族维生素"],
  },
  {
    id: "liver-case-2",
    solutionSlug: "liver",
    name: "赵先生",
    age: 36,
    location: "杭州",
    beforeState: ["经常熬夜到凌晨3-4点", "口气较重", "眼白部分状态不佳"],
    afterState: ["日常作息节奏有所改善", "口气问题有所缓解", "整体气色有所恢复"],
    duration: "服用水飞蓟宾+硫辛酸 8周后",
    timeline: "2024年7月",
    quote: "顾问说我是典型的作息紊乱型营养不足，调整饮食配合补充剂后，整体状态有比较明显的改善。",
    products: ["水飞蓟宾", "硫辛酸"],
  },
  {
    id: "liver-case-3",
    solutionSlug: "liver",
    name: "钱女士",
    age: 39,
    location: "武汉",
    beforeState: ["长期饮酒应酬", "饮酒后第二天头痛恶心", "体检显示部分肝指标异常"],
    afterState: ["饮酒后不适感有所减轻", "整体气色有所改善", "日常睡眠质量有所提升"],
    duration: "服用水飞蓟宾+NAC+复合B族 16周后",
    timeline: "2024年5月",
    quote: "我以为需要吃药才能改善，顾问建议先从护肝营养补充和调整生活方式开始。三个月后整体状态有比较明显的改善。",
    products: ["水飞蓟宾", "N-乙酰半胱氨酸", "B族维生素"],
  },
  // ===== 免疫支持方案 =====
  {
    id: "immune-case-1",
    solutionSlug: "immune",
    name: "周女士",
    age: 52,
    location: "北京",
    beforeState: ["换季时容易感冒", "感冒恢复周期较长", "日常精力容易透支"],
    afterState: ["换季时感冒次数有所减少", "感冒后恢复速度有所加快", "整体精力状态有所改善"],
    duration: "服用D3+K2+益生菌 12周后",
    timeline: "2024年3月",
    quote: "以前每到换季就要生病，服用营养师推荐的方案后，今年换季期间状态平稳多了。",
    products: ["维生素D3", "维生素K2", "益生菌"],
  },
  {
    id: "immune-case-2",
    solutionSlug: "immune",
    name: "林先生",
    age: 65,
    location: "福州",
    beforeState: ["体质较弱", "日常容易疲劳", "有慢性病史"],
    afterState: ["日常体力有所改善", "日常活动后不再明显气喘", "整体精力状态有所恢复"],
    duration: "服用D3+益生菌 16周后",
    timeline: "2024年5月",
    quote: "年龄大了不敢乱吃。顾问帮我评估后，只用了D3和益生菌，稳定又安全，状态有改善。",
    products: ["维生素D3", "益生菌"],
  },
  {
    id: "immune-case-3",
    solutionSlug: "immune",
    name: "郑女士",
    age: 45,
    location: "西安",
    beforeState: ["换季时容易感冒", "咽炎容易反复", "肠道敏感"],
    afterState: ["换季感冒次数有所减少", "咽炎发作频率有所降低", "肠道敏感问题有所改善"],
    duration: "服用D3+K2+益生菌 12周后",
    timeline: "2024年6月",
    quote: "顾问从肠道和维生素D3一起调理，现在换季期间状态稳定多了，整体身体状态有改善。",
    products: ["维生素D3", "维生素K2", "益生菌"],
  },
  // ===== 女性健康支持方案 =====
  {
    id: "female-case-1",
    solutionSlug: "female-health",
    name: "吴女士",
    age: 31,
    location: "上海",
    beforeState: ["经期前后疲劳明显", "经期不够规律", "气色偏暗"],
    afterState: ["经期前后疲劳感有所减轻", "周期整体规律性有所改善", "气色有所红润"],
    duration: "服用铁+叶酸+B族 10周后",
    timeline: "2024年4月",
    quote: "我一直以为自己需要大补，顾问建议我先做全面评估再对症补充。现在对症下药，效果很好。",
    products: ["氨基酸螯合铁", "甲基叶酸", "B族维生素"],
  },
  {
    id: "female-case-2",
    solutionSlug: "female-health",
    name: "黄女士",
    age: 42,
    location: "深圳",
    beforeState: ["经前综合征明显", "情绪波动较大", "睡眠质量差"],
    afterState: ["经前情绪稳定性有所改善", "睡眠质量有所提升", "皮肤状态有所改善"],
    duration: "服用D3+钙镁+B族 8周后",
    timeline: "2024年6月",
    quote: "顾问说我是经前综合征和维生素D缺乏叠加，补充了VD和镁，现在整体状态稳定多了。",
    products: ["维生素D3", "钙镁", "B族维生素"],
  },
  {
    id: "female-case-3",
    solutionSlug: "female-health",
    name: "许女士",
    age: 36,
    location: "苏州",
    beforeState: ["备孕半年未成功", "排卵期不够规律", "气色偏暗"],
    afterState: ["排卵周期规律性有所改善", "气色有所红润", "整体身体状态有所改善"],
    duration: "服用叶酸+辅酶Q10+铁 12周后",
    timeline: "2024年4月",
    quote: "顾问说我不只是营养不足问题，帮我调整了辅酶Q10和铁剂后，整体身体状态有明显改善。",
    products: ["辅酶Q10", "氨基酸螯合铁", "甲基叶酸"],
  },
  // ===== 男性健康支持方案 =====
  {
    id: "male-case-1",
    solutionSlug: "male-health",
    name: "周先生",
    age: 48,
    location: "北京",
    beforeState: ["日常精力有所下降", "应酬后恢复较慢", "体检显示部分指标异常"],
    afterState: ["日常精力状态有所改善", "应酬后第二天可以正常工作", "整体精力状态有所恢复"],
    duration: "服用玛卡+南非醉茄+锌 10周后",
    timeline: "2024年3月",
    quote: "顾问没有一来就推产品，先帮我分析饮食和作息。调整方案后，日常精力状态有明显改善。",
    products: ["玛卡提取物", "南非醉茄", "锌"],
  },
  {
    id: "male-case-2",
    solutionSlug: "male-health",
    name: "马先生",
    age: 35,
    location: "成都",
    beforeState: ["加班熬夜后第二天不在状态", "运动表现下降", "日常压力较大"],
    afterState: ["熬夜后第二天精力状态有所改善", "运动表现有所恢复", "日常抗压能力有所提升"],
    duration: "服用南非醉茄+辅酶Q10 8周后",
    timeline: "2024年5月",
    quote: "顾问推荐的方案帮我调整了身体对压力的反应，日常状态有明显改善。",
    products: ["南非醉茄", "辅酶Q10"],
  },
  {
    id: "male-case-3",
    solutionSlug: "male-health",
    name: "郑先生",
    age: 52,
    location: "重庆",
    beforeState: ["体检显示前列腺部分指标异常", "夜间起床次数较多影响睡眠", "整体精力下降"],
    afterState: ["夜间起床次数有所减少", "睡眠质量有所提升", "整体精力状态有所改善"],
    duration: "服用锯棕榈+锌+南非醉茄 12周后",
    timeline: "2024年7月",
    quote: "顾问说这是男性正常生理变化，不需要过度干预。调整了生活方式和营养补充后，整体状态有改善。",
    products: ["锯棕榈提取物", "锌", "南非醉茄"],
  },
];

export function getCasesBySlug(slug: string): CaseStudy[] {
  return caseStudies.filter((c) => c.solutionSlug === slug);
}
